name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1 Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3 Build project
      - name: Build Spark Pipelines Module
        run: mvn clean install
        working-directory: spark-pipelines

      - name: Build Search Service API Module
        run: mvn clean install
        working-directory: search-service

      # 4 Run tests
      - name: Run Tests spark pipelines
        run: mvn test
        working-directory: spark-pipelines

      - name: Run Tests Search Service API
        run: mvn test
        working-directory: search-service

      # 5 Upload JAR 
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      # 6 Add docker image build
      - name: Build Docker Image
        run: docker build -t product-search-app .
